// Here the first argument, 'state' is not the 
// application state, it is only the state
// this reducer is responsible for (which is 
// previously is generated by the BooksReducer)
export default function(state = null, action) {
  switch (action.type) {
    case 'BOOK_SELECTED':
      console.log('old state: ', state);
      console.log('new state: ', action.payload);
      return action.payload;
  }
  return state
}